server:
  port: 10083
  
#------------------------------------------------

spring: 
  cloud: 
    gateway:
      routes:
      - id: path_route_mongdb
        uri: http://localhost:8075
        predicates:
        - Path=/mongdb/*
        






